### ISSUE TITLE
Failure on Cobol fixed OCCURS (w/ PIC)

### ISSUE THREAD

**Issue by eanmclaughlin** [slott56/Stingray-Reader#3]
I have a copybook that includes a fixed OCCURS DDE with a PIC clause.

As far as I can tell, the copybook is parsed and the schema is built correctly, but when attempting to dump a workbook with the schema there is an exception in `expand_dims`.

This exception comes from having a DDE object in `dimensionality[0]`; this is extracted as `top` and passed to the built-in `range()` function, which (naturally) fails because it's not an integer.

See the following debug screenshot:
![image](https://user-images.githubusercontent.com/1026382/74198340-5a8ad800-4c1e-11ea-8bf8-82493307db0b.png)

Trace:
```
Traceback (most recent call last):
  File "~/git/Stingray-Reader/test.py", line 19, in <module>
    raw_dump(schema, sheet)
  File "~/git/Stingray-Reader/test.py", line 9, in raw_dump
    stingray.cobol.dump(schema, row)
  File "~/git/Stingray-Reader/stingray/cobol/__init__.py", line 393, in dump
    for aDDE, attr, indices, raw_bytes, cell in dump_iter(record, aRow):
  File "~/git/Stingray-Reader/stingray/cobol/__init__.py", line 381, in dump_iter
    for details in dump_iter( child, aRow ):
  File "~/git/Stingray-Reader/stingray/cobol/__init__.py", line 373, in dump_iter
    for indices in expand_dims( aDDE.dimensionality ):
  File "~/git/Stingray-Reader/stingray/cobol/__init__.py", line 368, in expand_dims
    for i in range(top):
TypeError: 'DDE' object cannot be interpreted as an integer
```
Test copybook:
```
       01  TEST-FORMAT.
         05  PRODUCT-CODE   OCCURS 6 TIMES PIC XX.
```

Test workbook:
```
123456789012
```

code:
```
import stingray.cobol.loader
import stingray.cobol
import pprint


def raw_dump(schema, sheet):
    for row in sheet.rows():
        stingray.cobol.dump(schema, row)


with open("sample/fixed_occurs.cob", "r") as cobol:
    schema = stingray.cobol.loader.COBOLSchemaLoader(cobol).load()
    pprint.pprint(schema)
    with stingray.cobol.Character_File('sample/fixed_test.txt', file_object=open("sample/fixed_test.txt", encoding="ascii"), schema=schema) as wb:
        sheet = wb.sheet('sample/fixed_test.txt')
        raw_dump(schema, sheet)
```

`pprint`'d schema:
```
Schema( Attribute( name='TEST-FORMAT', position=0, offset=0, size=12, dimensionality=() ), Attribute( name='PRODUCT-CODE', position=1, offset=0, size=2, dimensionality=(05 PRODUCT-CODE []) ) )
```
Evaluating `top.occurs.number(aRow)` while paused in the debugger properly returns `6`.

I tried changing the `range(top)` to `range(top.occurs.number(aRow))` but that results in:
```
  File "~/git/Stingray-Reader/stingray/cobol/__init__.py", line 374, in dump_iter
    yield aDDE, aDDE.attribute, indices, aRow.cell(attr,indices).raw, aRow.cell(attr,indices)
TypeError: cell() takes 2 positional arguments but 3 were given
```

**Comment by slott56** [comment]
There are a few subtle bugs in this. I'm in the process of rewriting it to add type hints. I'll add this as a unit test case.

**Comment by mahmoudimus** [comment]
In case this helps anyone else:

```python
def dump_iter( aDDE, aRow ):
    """Yields iterator over tuples of (dde, attribute, indices, bytes, Cell)"""
    def expand_dims( dimensionality, partial=() ):
        if not dimensionality:
            yield partial
            return
        top = dimensionality[0]
        rest= dimensionality[1:]
        for i in range(top.occurs.number(top.parent)):
            for e in expand_dims( rest, partial+(i,) ):
                yield e
    attr= aDDE.attribute() # Final size and offset details
    if aDDE.dimensionality:
        for indices in expand_dims( aDDE.dimensionality ):
            index = 0 if len(indices) != 1 else indices[0]
            raw = aRow.cell(attr)[index].raw
            yield aDDE, aDDE.attribute, indices, raw, aRow.cell(attr)
    elif aDDE.picture and aDDE.name != "FILLER":
        yield aDDE, aDDE.attribute(), (), aRow.cell(attr).raw, aRow.cell(attr)
    else: # FILLER or group level without a picture: no data is available
        yield aDDE, aDDE.attribute, (), None, None
    for child in aDDE.children:
        #pprint.pprint( child )
        for details in dump_iter( child, aRow ):
            yield details
```
